repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-yaml
    - id: check-toml
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
    - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
    - id: flake8

  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.1'
    hooks:
    - id: bandit
      args: [--skip=B101]

  - repo: https://github.com/pumpkin-py/pumpkin-tools
    rev: v1.7.0
    hooks:
    - id: popie
